---
# role: ansible-role-ipv6
# file: molecule/all/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ipv6-alpine
    image: "jam82/molecule-alpine:latest"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
  - name: ipv6-amazonlinux
    image: "jam82/molecule-amazonlinux:latest"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-arch
    image: "jam82/molecule-archlinux:latest"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-centos6
    image: "jam82/molecule-centos:6"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
  - name: ipv6-centos7
    image: "jam82/molecule-centos:7"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-centos8
    image: "jam82/molecule-centos:8"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-debian9
    image: "jam82/molecule-debian:9"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-debian10
    image: "jam82/molecule-debian:10"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-opensuse15
    image: "jam82/molecule-opensuse:15"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-opensuse-tumbleweed
    image: "jam82/molecule-opensuse:tumbleweed"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-oraclelinux6
    image: "jam82/molecule-oraclelinux:6"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
  - name: ipv6-oraclelinux7
    image: "jam82/molecule-oraclelinux:7"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-oraclelinux8
    image: "jam82/molecule-oraclelinux:8"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-ubuntu1604
    image: "jam82/molecule-ubuntu:16.04"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-ubuntu1804
    image: "jam82/molecule-ubuntu:18.04"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: ipv6-ubuntu2004
    image: "jam82/molecule-ubuntu:20.04"
    pre_build_image: True
    privileged: True
    tmpfs:
      - /tmp
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
  log: True
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
  inventory:
    group_vars:
      all:
        ipv6_role_enabled: True
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore"
  directory: ../resources/tests
  options:
    v: True
    sudo: True
