---
# role: ansible-role-ipv6
# file: .travis.yml

os: linux
dist: focal
language: python
python: "3.9"
services: docker

env:
  global:
    - TOX_PARALLEL_NO_SPINNER: 1
  matrix:
    - MOLECULE_DIST: 'jam82/molecule-alpine:latest'
    - MOLECULE_DIST: 'jam82/molecule-amazonlinux:latest'
    - MOLECULE_DIST: 'jam82/molecule-archlinux:latest'
    - MOLECULE_DIST: 'jam82/molecule-centos:7'
    - MOLECULE_DIST: 'jam82/molecule-centos:8'
    - MOLECULE_DIST: 'jam82/molecule-debian:9'
    - MOLECULE_DIST: 'jam82/molecule-debian:10'
    - MOLECULE_DIST: 'jam82/molecule-debian:11'
    - MOLECULE_DIST: 'jam82/molecule-opensuse:15'
    - MOLECULE_DIST: 'jam82/molecule-opensuse:tumbleweed'
    - MOLECULE_DIST: 'jam82/molecule-oraclelinux:7'
    - MOLECULE_DIST: 'jam82/molecule-oraclelinux:8'
    - MOLECULE_DIST: 'jam82/molecule-ubuntu:18.04'
    - MOLECULE_DIST: 'jam82/molecule-ubuntu:20.04'

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel
