---
# role: ansible-role-ipv6
# file: handlers/main.yml

- name: modprobe ipv6
  command: "modprobe {{ ipv6_modprobe_options }} ipv6"

- name: restart networking
  service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ ipv6_networking_services }}"
